# -*- coding: utf-8 -*-
##
## This file is part of ADSWS
## Copyright (C) 2014 ADSLABS
##
## ADSWS is free software; you can redistribute it and/or
## modify it under the terms of the GNU General Public License as
## published by the Free Software Foundation; either version 2 of the
## License, or (at your option) any later version.


# Travis CI file, that integrates with coveralls for reporting test coverage.

language: python

python:
  - "2.7"

env:
  #- REQUIREMENTS=lowest
  #- REQUIREMENTS=release
  - REQUIREMENTS=devel

services:
  - redis-server

install:
  - "pip install --upgrade pip  --use-mirrors"
  - "pip install coveralls pep257 --use-mirrors"
  - "pip install pytest pytest-pep8 pytest-cov pytest-cache --use-mirrors"
  - "pip install -r requirements.txt"
  - "pip install -r .travis-$REQUIREMENTS-requirements.txt"

script:
  - "py.test adsws"

after_success:
  - "coveralls"

notifications:
  email: false
